### ISSUE TITLE
Error Message: String is not in a unique standard format

### ISSUE THREAD

**Issue by JoshSchramm94** [sem-in-r/seminr#251]
Hey there,

I was working with the A Primer on Partial Least Squares Structural Equation Modeling (PLS-SEM) book by Hair, Hult, Ringle, and Sarstedt (already waiting for the 3rd edition including R) and found the R codes on the seminr page on github. I was trying to use the package and constructing a model, however, I got the following error message: 

Generating the seminr model
Error in as.POSIXlt.character(x, tz, ...) : 
Zeichenkette ist nicht in einem eindeutigen Standardformat (probaby something like "Error Message: String is not in a unique standard format" in English). 

The following was my script (there is no sense yet, as I was just trying to play around with the script a little bit): 

mm <- constructs(
  composite("iNFT", multi_items("iNFT", 1:6)),
  composite("aNFT", multi_items("aNFT",1:6)),
  composite("Fun", multi_items("fun",1:4))
)

simple_sm <- relationships(
  paths(from = "iNFT", to = c("aNFT")),
  paths(from = "iNFT", to = c("Fun"))
)

corp_rep_pls_model_ext <- estimate_pls(data = d2,
  measurement_model = mm,
  structural_model  = simple_sm,
  missing = mean_replacement,
  missing_value = "-99")

Another issue I was facing is that I also wanted to include a binary variable or a mediator which was only measured by one variable (and not really meant as a construct). As this is possible in the Smart PLS application I was wondering how the code looks like working with your package in R. I tried to only include it in the structural model as well as defining it as a construct in the measurement model, however, both approaches did not work. 

It would be awesome if you can help me out. 

Thanks a lot for taking the time.
Joshua

**Comment by NicholasDanks** [comment]
Dear Joshua,

I hope you are well and thanks for your interest in the package. 
First of all we now have an open-access version of the primer: https://link.springer.com/book/10.1007/978-3-030-80519-7
Please do download and check it out. 

Regarding the bug you encounter, I have tried to reproduce it by creating a "simulated" dataset by using the mobi data with renamed columns. See the below code:  
```
d2 <- mobi[,1:16]

colnames(d2) <- c(multi_items("iNFT", 1:6), multi_items("aNFT",1:6), multi_items("fun",1:4))

mm <- constructs(
  composite("iNFT", multi_items("iNFT", 1:6)),
  composite("aNFT", multi_items("aNFT",1:6)),
  composite("Fun", multi_items("fun",1:4))
)

simple_sm <- relationships(
  paths(from = "iNFT", to = c("aNFT")),
  paths(from = "iNFT", to = c("Fun"))
)

corp_rep_pls_model_ext <- estimate_pls(data = d2,
                                       measurement_model = mm,
                                       structural_model = simple_sm,
                                       missing = mean_replacement,
                                       missing_value = "-99")

```
However, I cannot seem to replicate your error.
Could you try again to run the above code? If the above code does not error, then you can assume the bug is in your data (perhaps data column names are not correctly spelled.)
If you find the bug persists, please run sessionInfo() and let us know the output from this and the output from your bug.

Regarding the single item constructs, we have a solution by using the following code to define the 

```
composite("CUSA", single_item("cusa")),
```
You can find ana example deploying this in our demo file:
seminr-primer-chap4 by running the following code:

```
library(seminr)
demo("seminr-primer-chap4")
```

As for binary variables, this is a debatable topic. If the binary construct is an antecedent, it should be OK. However, if the binary construct is a outcome construct then technically you should be running a logistic regression in the structural regressions. This has not been implemented in any software that I am aware of. 

If your bug is resolved, please close this issue. 

Hope this helps and happy modeling. 
Nick
