### ISSUE TITLE
handle size of PLS-SEM plot

### ISSUE THREAD

**Issue by alibezzaa** [sem-in-r/seminr#311]
I have a model with many indicators, and I cannot decipher the significant from the nonsignificant paths when I use the plot() function on the bootstrapped model. I have two questions: 
How can we eliminate the loadings from the constructs to the indicators (reflective)?
How to improve the overall appearance of the model, and make it ready for publication?

**Comment by NicholasDanks** [comment]
Dear Alibezzaa,

Thank you very much for this great request. In general, the GitHub page is for feature requests, issues, and bugs in the code.  Since this question is more related to the application of the package, it would be more useful to post it on the FB page so that other users might benefit from the discussion. 

1. How can we eliminate the loadings from the constructs to the indicators (reflective)?
Im not sure what this means? You could try to run the plot() command on the measurement_model object. This will yield a plot with no loadings. 
![image](https://user-images.githubusercontent.com/17057395/192737309-e3a30657-f801-4daf-b257-f347bfeea121.png)
If this doesn't work, please clarify your question in more detail.

2. You can create a model in PPT and design it exactly as you want. I do this. 

Keep well.

**Comment by alibezzaa** [comment]
Thank you for your reply. 
I wanted to know if it is possible, with SEMinR, to plot only the structural model **without** the outer loadings, as it is possible with SmartPLS. This way the plot is lighter and easier to interpret.

**Comment by NicholasDanks** [comment]
Dear Alibezzaa,

Please can you post this query on our Facebook page as this forum is for code-related bugs and issues.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: alibezzaa ***@***.***>
Sent: Saturday, September 24, 2022 8:41:24 AM
To: sem-in-r/seminr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sem-in-r/seminr] handle size of PLS-SEM plot (Issue #311)


I have a model with many indicators, and I cannot decipher the significant from the nonsignificant paths when I use the plot() function on the bootstrapped model. I have two questions:
How can we eliminate the paths from the constructs to the indicators (reflective)?
How to improve the overall appearance of the model, and make it ready for publication?
